apiVersion: v1
baseDomain: minhaempresa.com
metadata:
  name: meucluster
platform:
  aws:
    region: us-east-1
publish: External
controlPlane:
  name: master
  replicas: 3
  platform:
    aws:
      type: m6i.xlarge
      rootVolume:
        size: 300
        type: gp3
  hyperthreading: Enabled
compute:
- name: worker
  replicas: 3
  platform:
    aws:
      type: m6i.xlarge
      rootVolume:
        size: 300
        type: gp3
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
  machineNetwork:
  - cidr: 10.0.0.0/16
fips: false
pullSecret: '<COLE_AQUI_O_JSON_DA_PULL_SECRET>'
sshKey: 'ssh-ed25519 AAAA...seu_ssh_publico...'
